version: '2'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:mysecretpasswod@postgresql:5432
    volumes:
      - .:/app
    command: ['bundle', 'exec', 'rails', 's', '-p', '5000',  '-b', '0.0.0.0']
    depends_on:
      - postgresql

  postgresql:
    image: postgres:9.5.5
